GridLayout:
    cols: 1
    rows: 2
    padding: 20
    spacing: 5

    Label:
        id: label
        text: app.label
        font_size: 32

    GridLayout:
        cols: 4
        rows: 6
        padding: 20
        spacing: 5

        Button:
            text: 'CE'
            on_press: app.presser(self.text)
        Button:
            text: 'X'
            on_press: app.presser(self.text)
        Button:
            text: '%'
            on_press: app.presser(self.text)
        Button:
            text: '÷'
            on_press: app.presser(self.text)
        Button:
            text: '7'
            on_press: app.presser(self.text)
        Button:
            text: '8'
            on_press: app.presser(self.text)
        Button:
            text: '9'
            on_press: app.presser(self.text)
        Button:
            text: '×'
            on_press: app.presser(self.text)
        Button:
            text: '4'
            on_press: app.presser(self.text)
        Button:
            text: '5'
            on_press: app.presser(self.text)
        Button:
            text: '6'
            on_press: app.presser(self.text)
        Button:
            text: '-'
            on_press: app.presser(self.text)
        Button:
            text: '1'
            on_press: app.presser(self.text)
        Button:
            text: '2'
            on_press: app.presser(self.text)
        Button:
            text: '3'
            on_press: app.presser(self.text)
        Button:
            text: '+'
            on_press: app.presser(self.text)
        Button:
            text: '0'
            on_press: app.presser(self.text)
        Button:
            text: '.'
            on_press: app.presser(self.text)
        Button:
            text: '+/-'
            on_press: app.presser(self.text)
        Button:
            text: '='
            on_press: app.presser(self.text)