GridLayout:
    cols: 1
    rows: 2
    padding: 20
    spacing: 5

    Label:
        id: label
        text: app.label
        font_size: 45

    GridLayout:
        cols: 4
        rows: 6
        padding: 20
        spacing: 5

        Button:
            text: 'CE'
            on_press: app.presser(self.text)
            background_normal: ''
            background_color: (0.188, 0.108, 0.37, 1)
            font_size: 40
        Button:
            text: ''
            background_color: 0, 0, 0, 0
        Button:
            text: '÷'
            on_press: app.presser(self.text)
            background_normal: ''
            background_color: (0.40, 0.54, 0.24, 1)
            font_size: 40
        Button:
            text: '×'
            on_press: app.presser(self.text)
            background_normal: ''
            background_color: (0.40, 0.54, 0.24, 1)
            font_size: 40
        Button:
            text: '7'
            on_press: app.presser(self.text)
            font_size: 40
        Button:
            text: '8'
            on_press: app.presser(self.text)
            font_size: 40
        Button:
            text: '9'
            on_press: app.presser(self.text)
            font_size: 40
        Button:
            text: '-'
            on_press: app.presser(self.text)
            background_normal: ''
            background_color: (0.40, 0.54, 0.24, 1)
            font_size: 40
        Button:
            text: '4'
            on_press: app.presser(self.text)
            font_size: 40
        Button:
            text: '5'
            on_press: app.presser(self.text)
            font_size: 40
        Button:
            text: '6'
            on_press: app.presser(self.text)
            font_size: 40
        Button:
            text: '+'
            on_press: app.presser(self.text)
            background_normal: ''
            background_color: (0.40, 0.54, 0.24, 1)
            font_size: 40
        Button:
            text: '1'
            on_press: app.presser(self.text)
            font_size: 40
        Button:
            text: '2'
            on_press: app.presser(self.text)
            font_size: 40
        Button:
            text: '3'
            on_press: app.presser(self.text)
            font_size: 40
        Button:
            text: '='
            on_press: app.presser(self.text)
            background_normal: ''
            background_color: (0.188, 0.108, 0.37, 1)
            font_size: 40
        Button:
            text: ''
            background_color: 0, 0, 0, 0
        Button:
            text: '0'
            on_press: app.presser(self.text)
            font_size: 40