GridLayout:
    cols: 1
    rows: 2
    padding: 20
    spacing: 5

    Label:
        id: label
        font_size: 45

    GridLayout:
        cols: 4
        rows: 6
        padding: 20
        spacing: 5

        Button:
            text: 'CE'
            on_press: label.text=''
            background_normal: ''
            background_color: (0.188, 0.108, 0.37, 1)
            font_size: 40
        Button:
            text: ''
            background_color: 0, 0, 0, 0
        Button:
            text: '÷'
            on_press: label.text+='/'
            background_normal: ''
            background_color: (0.40, 0.54, 0.24, 1)
            font_size: 40
        Button:
            text: '×'
            on_press: label.text+='*'
            background_normal: ''
            background_color: (0.40, 0.54, 0.24, 1)
            font_size: 40
        Button:
            text: '7'
            on_press: label.text+='7'
            font_size: 40
        Button:
            text: '8'
            on_press: label.text+='8'
            font_size: 40
        Button:
            text: '9'
            on_press: label.text+='9'
            font_size: 40
        Button:
            text: '-'
            on_press: label.text+='-'
            background_normal: ''
            background_color: (0.40, 0.54, 0.24, 1)
            font_size: 40
        Button:
            text: '4'
            on_press: label.text+='4'
            font_size: 40
        Button:
            text: '5'
            on_press: label.text+='5'
            font_size: 40
        Button:
            text: '6'
            on_press: label.text+='6'
            font_size: 40
        Button:
            text: '+'
            on_press: label.text+='+'
            background_normal: ''
            background_color: (0.40, 0.54, 0.24, 1)
            font_size: 40
        Button:
            text: '1'
            on_press: label.text+='1'
            font_size: 40
        Button:
            text: '2'
            on_press: label.text+='2'
            font_size: 40
        Button:
            text: '3'
            on_press: label.text+='3'
            font_size: 40
        Button:
            text: '='
            on_press: label.text=str(eval(label.text))
            background_normal: ''
            background_color: (0.188, 0.108, 0.37, 1)
            font_size: 40
        Button:
            text: ''
            background_color: 0, 0, 0, 0
        Button:
            text: '0'
            on_press: label.text+='0'
            font_size: 40